#!/usr/bin/env node
// Generates sitemap.xml from the pages the site actually publishes.
//
// Why this exists
// ---------------
// sitemap.xml used to be hand-maintained at the repository root while
// /insights/ is generated by Eleventy from /src/. The two cannot stay in step
// by construction, and they did not: seven of ten articles were indexable,
// linked, and absent from the sitemap. Every new article would have joined
// them.
//
// The fix is not "remember to update the sitemap". It is to derive the
// sitemap from the same page inventory the deploy uses, so omission becomes
// impossible rather than merely discouraged.
//
// Where the inventory comes from
// ------------------------------
// scripts/build-publish.mjs already walks the root, applies the deny list and
// therefore knows exactly which files ship. This script imports that same
// walk. Deriving the sitemap from Eleventy instead would have been wrong in
// the opposite direction: Eleventy owns 10 of 54 pages, so it would have
// listed the articles and dropped the 44 hand-maintained root pages.
//
// Two things this must get right
// ------------------------------
// 1. URLs are extensionless (PR #49). Composing site.url + filename would
//    silently write .html back into the sitemap and undo that change with no
//    gate catching it. Hence urlFor(), and the assertion at the end.
// 2. The output is written into the repository, not only into a build
//    directory. GitHub Pages serves from the root and remains the rollback
//    until the Cloudflare migration has been stable for seven days; a sitemap
//    that only existed at Pages-build time would leave the rollback serving a
//    stale file.
//
// Curated metadata (lastmod, changefreq, priority) lives in
// scripts/sitemap-meta.json and is owned by a human. A page with no entry
// still gets published to the sitemap — with defaults derived from its path,
// and no lastmod at all — because a missing priority must never be the reason
// a page goes unindexed. The output depends only on the working tree, never
// on git history or the current date; see the note above urlFor().
//
// Usage:  node scripts/build-sitemap.mjs [--check]
//         --check exits non-zero if the committed sitemap.xml differs from a
//         fresh generation, without writing. This is the CI gate: the same
//         shape as Eleventy Build Verify, asserting something true or false
//         rather than something that merely looks right.

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { collectPublishedFiles } from './build-publish.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ORIGIN = 'https://stevenwensley.com';
const OUT = join(ROOT, 'sitemap.xml');

const meta = JSON.parse(await readFile(join(ROOT, 'scripts/sitemap-meta.json'), 'utf8'));

// Public URL for a published file. Extensionless — see note 1 above.
const urlFor = (file) => (file === 'index.html' ? '/' : '/' + file.replace(/\.html$/, ''));

// There is deliberately no lastmod fallback. Two were tried and both were
// wrong:
//
//   git log -1 -- <file>   Non-deterministic. GitHub Actions checks out with
//                          fetch-depth 1, so the file's last commit is usually
//                          not in the clone and the lookup returns nothing.
//                          The gate then failed in CI while passing locally.
//                          It was also dishonest: a site-wide sweep that
//                          touched every file would restamp every article as
//                          modified that day.
//   new Date()             Makes the generator's output depend on the day it
//                          runs, so a committed, gate-checked file disagrees
//                          with itself tomorrow.
//
// lastmod is optional in the sitemap protocol. A page nobody has curated is
// published without one rather than with an invented one — the articles carry
// no publication date anywhere in the source, so there is nothing honest to
// put there.

// Defaults for a page nobody has curated. Deliberately unambitious: the point
// is that the page is listed at all.
const defaultsFor = (url) => {
  if (url.startsWith('/insights/')) return { changefreq: 'monthly', priority: '0.7' };
  if (url.startsWith('/note-') || url.startsWith('/playbook-')) return { changefreq: 'monthly', priority: '0.7' };
  return { changefreq: 'monthly', priority: '0.6' };
};

const files = (await collectPublishedFiles()).filter((f) => f.endsWith('.html'));

const entries = [];
const uncurated = [];

for (const file of files) {
  const html = await readFile(join(ROOT, file), 'utf8');
  if (/<meta[^>]*name\s*=\s*["']robots["'][^>]*noindex/i.test(html)) continue;
  if (file === '404.html') continue;

  const url = urlFor(file);
  const curated = meta[url];
  if (!curated) uncurated.push(url);

  const d = defaultsFor(url);
  entries.push({
    loc: ORIGIN + url,
    lastmod: curated?.lastmod ?? null,
    changefreq: curated?.changefreq ?? d.changefreq,
    priority: curated?.priority ?? d.priority,
  });
}

entries.sort((a, b) => Number(b.priority) - Number(a.priority) || a.loc.localeCompare(b.loc));

const xml =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  entries
    .map(
      (e) =>
        '  <url>\n' +
        `    <loc>${e.loc}</loc>\n` +
        (e.lastmod ? `    <lastmod>${e.lastmod}</lastmod>\n` : '') +
        `    <changefreq>${e.changefreq}</changefreq>\n` +
        `    <priority>${e.priority}</priority>\n` +
        '  </url>\n'
    )
    .join('') +
  '</urlset>\n';

// Assertion, not a hope: the extensionless migration must not regress here.
const bad = entries.filter((e) => /\.html(\?|#|$)/.test(e.loc));
if (bad.length) {
  console.error('build-sitemap: FEJL — .html-URL i sitemap:');
  for (const b of bad) console.error(`  ${b.loc}`);
  process.exit(1);
}

const check = process.argv.includes('--check');
const existing = await readFile(OUT, 'utf8').catch(() => '');

if (check) {
  if (existing !== xml) {
    console.error(
      'build-sitemap: FEJL — committet sitemap.xml matcher ikke en frisk generering.\n' +
        '  Kør: node scripts/build-sitemap.mjs  og commit resultatet.'
    );
    const was = new Set([...existing.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]));
    const now = new Set(entries.map((e) => e.loc));
    for (const u of now) if (!was.has(u)) console.error(`  mangler i committet fil:  ${u}`);
    for (const u of was) if (!now.has(u)) console.error(`  overflødig i committet fil: ${u}`);
    process.exit(1);
  }
  console.log(`build-sitemap: committet sitemap.xml er ajour (${entries.length} URL'er)`);
} else {
  await writeFile(OUT, xml, 'utf8');
  console.log(`build-sitemap: ${entries.length} URL'er skrevet til sitemap.xml`);
}

if (uncurated.length) {
  console.log(
    `build-sitemap: ${uncurated.length} side(r) uden kurateret metadata — udgivet med standardvaerdier:`
  );
  for (const u of uncurated.sort()) console.log(`  ${u}`);
}
